cmake_minimum_required(VERSION 3.20)

get_filename_component(_script_dir "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
get_filename_component(_windows_build_dir "${_script_dir}/.." ABSOLUTE)
get_filename_component(_default_source_root "${_windows_build_dir}/.." ABSOLUTE)
get_filename_component(_default_workspace_root "${_default_source_root}/../windows_build" ABSOLUTE)
include("${_script_dir}/kf6-sdk-common.cmake")

scholia_default_path(SOURCE_ROOT "${_default_source_root}")
scholia_default_path(WORKSPACE_ROOT "${_default_workspace_root}")
scholia_default_path(SDK_PREFIX "${WORKSPACE_ROOT}/sdk")

if(NOT DEFINED GETTEXT_VERSION OR "${GETTEXT_VERSION}" STREQUAL "")
    set(GETTEXT_VERSION "1.0")
endif()
if(NOT DEFINED ICONV_VERSION OR "${ICONV_VERSION}" STREQUAL "")
    set(ICONV_VERSION "1.19")
endif()
set(_release_tag "v${GETTEXT_VERSION}-v${ICONV_VERSION}")
set(_archive_name "gettext${GETTEXT_VERSION}-iconv${ICONV_VERSION}-static-64.zip")
set(_archive_sha256 "2B999BC37B56FA052FF98578E9CB188152009F634E3A66AA8FF263A016E9C466")
set(_url "https://github.com/mlocati/gettext-iconv-windows/releases/download/${_release_tag}/${_archive_name}")
set(_download_dir "${WORKSPACE_ROOT}/downloads")
set(_archive "${_download_dir}/${_archive_name}")
set(_tools_root "${SDK_PREFIX}/tools")
set(_install_dir "${_tools_root}/gettext-native")

message(STATUS "Scholia SDK native gettext install")
message(STATUS "  Version   : gettext ${GETTEXT_VERSION}, iconv ${ICONV_VERSION}")
message(STATUS "  SdkPrefix : ${SDK_PREFIX}")
message(STATUS "  URL       : ${_url}")

file(MAKE_DIRECTORY "${_download_dir}" "${_tools_root}")
if(NOT EXISTS "${_archive}")
    file(DOWNLOAD "${_url}" "${_archive}" EXPECTED_HASH "SHA256=${_archive_sha256}" SHOW_PROGRESS)
else()
    file(SHA256 "${_archive}" _actual_sha256)
    string(TOLOWER "${_archive_sha256}" _expected_sha256_lower)
    string(TOLOWER "${_actual_sha256}" _actual_sha256_lower)
    if(NOT _actual_sha256_lower STREQUAL _expected_sha256_lower)
        file(REMOVE "${_archive}")
        file(DOWNLOAD "${_url}" "${_archive}" EXPECTED_HASH "SHA256=${_archive_sha256}" SHOW_PROGRESS)
    endif()
endif()

scholia_remove_inside("${_install_dir}" "${_tools_root}")
file(MAKE_DIRECTORY "${_install_dir}")
file(ARCHIVE_EXTRACT INPUT "${_archive}" DESTINATION "${_install_dir}")
if(NOT EXISTS "${_install_dir}/bin/msgfmt.exe")
    message(FATAL_ERROR "Downloaded gettext archive did not contain bin/msgfmt.exe.")
endif()
execute_process(COMMAND "${_install_dir}/bin/msgfmt.exe" --version OUTPUT_VARIABLE _out ERROR_VARIABLE _err RESULT_VARIABLE _result)
if(NOT _result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "GNU gettext-tools")
    message(FATAL_ERROR "Installed msgfmt did not look like GNU gettext-tools: ${_install_dir}/bin/msgfmt.exe")
endif()

file(WRITE "${SDK_PREFIX}/scholia-sdk-gettext-native.cmake"
"set(SCHOLIA_GETTEXT_NATIVE_VERSION \"${GETTEXT_VERSION}\")
set(SCHOLIA_GETTEXT_NATIVE_ICONV_VERSION \"${ICONV_VERSION}\")
set(SCHOLIA_GETTEXT_NATIVE_URL \"${_url}\")
set(SCHOLIA_GETTEXT_NATIVE_SHA256 \"${_archive_sha256}\")
")
message(STATUS "Installed native gettext into SDK: ${_install_dir}/bin/msgfmt.exe")
