cmake_minimum_required(VERSION 3.20)

get_filename_component(_script_dir "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
get_filename_component(_windows_build_dir "${_script_dir}/.." ABSOLUTE)
get_filename_component(_default_source_root "${_windows_build_dir}/.." ABSOLUTE)
get_filename_component(_default_workspace_root "${_default_source_root}/../windows_build" ABSOLUTE)
include("${_script_dir}/kf6-sdk-common.cmake")

scholia_default_path(SOURCE_ROOT "${_default_source_root}")
scholia_default_path(WORKSPACE_ROOT "${_default_workspace_root}")
scholia_default_path(SDK_PREFIX "${WORKSPACE_ROOT}/sdk")

if(NOT DEFINED WINFLEXBISON_VERSION OR "${WINFLEXBISON_VERSION}" STREQUAL "")
    set(WINFLEXBISON_VERSION "2.5.25")
endif()
set(_archive_name "win_flex_bison-${WINFLEXBISON_VERSION}.zip")
set(_archive_sha256 "8D324B62BE33604B2C45AD1DD34AB93D722534448F55A16CA7292DE32B6AC135")
set(_url "https://github.com/lexxmark/winflexbison/releases/download/v${WINFLEXBISON_VERSION}/${_archive_name}")
set(_download_dir "${WORKSPACE_ROOT}/downloads")
set(_archive "${_download_dir}/${_archive_name}")
set(_tools_dir "${SDK_PREFIX}/tools/winflexbison-${WINFLEXBISON_VERSION}")
set(_bin_dir "${SDK_PREFIX}/bin")

message(STATUS "Scholia SDK winflexbison install")
message(STATUS "  Version   : ${WINFLEXBISON_VERSION}")
message(STATUS "  SdkPrefix : ${SDK_PREFIX}")
message(STATUS "  URL       : ${_url}")

file(MAKE_DIRECTORY "${_download_dir}" "${_bin_dir}")
if(NOT EXISTS "${_archive}")
    file(DOWNLOAD "${_url}" "${_archive}" EXPECTED_HASH "SHA256=${_archive_sha256}" SHOW_PROGRESS)
else()
    file(SHA256 "${_archive}" _actual_sha256)
    string(TOLOWER "${_archive_sha256}" _expected_sha256_lower)
    string(TOLOWER "${_actual_sha256}" _actual_sha256_lower)
    if(NOT _actual_sha256_lower STREQUAL _expected_sha256_lower)
        file(REMOVE "${_archive}")
        file(DOWNLOAD "${_url}" "${_archive}" EXPECTED_HASH "SHA256=${_archive_sha256}" SHOW_PROGRESS)
    endif()
endif()

scholia_remove_inside("${_tools_dir}" "${SDK_PREFIX}/tools")
file(MAKE_DIRECTORY "${_tools_dir}")
file(ARCHIVE_EXTRACT INPUT "${_archive}" DESTINATION "${_tools_dir}")
file(GLOB_RECURSE _win_flex "${_tools_dir}/win_flex.exe")
file(GLOB_RECURSE _win_bison "${_tools_dir}/win_bison.exe")
file(GLOB_RECURSE _data_dirs LIST_DIRECTORIES true "${_tools_dir}/data")
list(GET _win_flex 0 _win_flex_exe)
list(GET _win_bison 0 _win_bison_exe)
list(GET _data_dirs 0 _tool_data)
if(NOT EXISTS "${_win_flex_exe}" OR NOT EXISTS "${_win_bison_exe}" OR NOT IS_DIRECTORY "${_tool_data}")
    message(FATAL_ERROR "Downloaded winflexbison archive did not contain win_flex.exe, win_bison.exe, and data resources.")
endif()
file(COPY_FILE "${_win_flex_exe}" "${_bin_dir}/win_flex.exe")
file(COPY_FILE "${_win_bison_exe}" "${_bin_dir}/win_bison.exe")
file(COPY_FILE "${_win_flex_exe}" "${_bin_dir}/flex.exe")
file(COPY_FILE "${_win_bison_exe}" "${_bin_dir}/bison.exe")
file(MAKE_DIRECTORY "${_bin_dir}/data")
file(COPY "${_tool_data}/" DESTINATION "${_bin_dir}/data")

file(WRITE "${SDK_PREFIX}/scholia-sdk-winflexbison.cmake"
"set(SCHOLIA_WINFLEXBISON_VERSION \"${WINFLEXBISON_VERSION}\")
set(SCHOLIA_WINFLEXBISON_URL \"${_url}\")
set(SCHOLIA_WINFLEXBISON_SHA256 \"${_archive_sha256}\")
")
message(STATUS "Installed winflexbison into SDK bin.")
