cmake_minimum_required(VERSION 3.20)

function(scholia_default_path variable default_value)
    if(NOT DEFINED ${variable} OR "${${variable}}" STREQUAL "")
        set(${variable} "${default_value}" PARENT_SCOPE)
    else()
        get_filename_component(_absolute_value "${${variable}}" ABSOLUTE)
        set(${variable} "${_absolute_value}" PARENT_SCOPE)
    endif()
endfunction()

function(scholia_find_qt_prefix out_var)
    set(_candidates)
    if(DEFINED QT_PREFIX AND NOT "${QT_PREFIX}" STREQUAL "")
        list(APPEND _candidates "${QT_PREFIX}")
    endif()
    if(DEFINED ENV{QTDIR})
        list(APPEND _candidates "$ENV{QTDIR}")
    endif()
    if(DEFINED ENV{Qt6_DIR})
        get_filename_component(_qt_from_config "$ENV{Qt6_DIR}/../../.." ABSOLUTE)
        list(APPEND _candidates "${_qt_from_config}")
    endif()
    file(GLOB _qt_roots LIST_DIRECTORIES true "C:/Qt/*/msvc2022_64")
    list(APPEND _candidates ${_qt_roots})

    foreach(_candidate IN LISTS _candidates)
        if(EXISTS "${_candidate}/lib/cmake/Qt6/Qt6Config.cmake")
            get_filename_component(_qt "${_candidate}" ABSOLUTE)
            set(${out_var} "${_qt}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    message(FATAL_ERROR "Cannot find a Qt MSVC prefix. Pass -DQT_PREFIX=C:/Qt/<version>/msvc2022_64.")
endfunction()

function(scholia_find_program out_var)
    foreach(_candidate IN LISTS ARGN)
        if(EXISTS "${_candidate}")
            get_filename_component(_program "${_candidate}" ABSOLUTE)
            set(${out_var} "${_program}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    find_program(_program_from_path NAMES "${out_var}")
    if(_program_from_path)
        set(${out_var} "${_program_from_path}" PARENT_SCOPE)
        return()
    endif()
    message(FATAL_ERROR "Cannot find ${out_var}.")
endfunction()

function(scholia_find_toolchain)
    scholia_find_qt_prefix(QT_PREFIX_RESOLVED)
    set(QT_PREFIX "${QT_PREFIX_RESOLVED}" PARENT_SCOPE)

    if(DEFINED CMAKE_EXE AND NOT "${CMAKE_EXE}" STREQUAL "")
        set(CMAKE_PROGRAM "${CMAKE_EXE}" PARENT_SCOPE)
    else()
        set(CMAKE_PROGRAM "${CMAKE_COMMAND}" PARENT_SCOPE)
    endif()

    if(DEFINED NINJA AND NOT "${NINJA}" STREQUAL "")
        get_filename_component(_ninja "${NINJA}" ABSOLUTE)
        set(NINJA_PROGRAM "${_ninja}" PARENT_SCOPE)
    else()
        scholia_find_program(NINJA_PROGRAM
            "${QT_PREFIX_RESOLVED}/../../Tools/Ninja/ninja.exe"
            "C:/Program Files/Ninja/ninja.exe"
        )
        set(NINJA_PROGRAM "${NINJA_PROGRAM}" PARENT_SCOPE)
    endif()

    if(NOT DEFINED VCVARS OR "${VCVARS}" STREQUAL "")
        set(VCVARS "C:/Program Files/Microsoft Visual Studio/18/Community/VC/Auxiliary/Build/vcvars64.bat" PARENT_SCOPE)
    else()
        get_filename_component(_vcvars "${VCVARS}" ABSOLUTE)
        set(VCVARS "${_vcvars}" PARENT_SCOPE)
    endif()
endfunction()

function(scholia_remove_inside path allowed_root)
    get_filename_component(_path "${path}" ABSOLUTE)
    get_filename_component(_allowed "${allowed_root}" ABSOLUTE)
    string(FIND "${_path}" "${_allowed}" _position)
    if(NOT _position EQUAL 0)
        message(FATAL_ERROR "Refusing to remove path outside ${_allowed}: ${_path}")
    endif()
    if(EXISTS "${_path}")
        file(REMOVE_RECURSE "${_path}")
    endif()
endfunction()

function(scholia_prepare_build_dir build_dir allowed_root source_dir)
    set(_remove_build_dir OFF)
    if(EXISTS "${build_dir}/CMakeCache.txt")
        file(READ "${build_dir}/CMakeCache.txt" _cache)
        string(REGEX MATCH "CMAKE_HOME_DIRECTORY:INTERNAL=([^\r\n]+)" _match "${_cache}")
        if(CMAKE_MATCH_1)
            get_filename_component(_cached_source "${CMAKE_MATCH_1}" ABSOLUTE)
            get_filename_component(_requested_source "${source_dir}" ABSOLUTE)
            if(NOT _cached_source STREQUAL _requested_source)
                message(STATUS "Removing stale CMake build dir with source ${_cached_source}: ${build_dir}")
                set(_remove_build_dir ON)
            endif()
        endif()
        string(REGEX MATCH "CMAKE_C_COMPILER:FILEPATH=([^\r\n]+)" _compiler_match "${_cache}")
        if(CMAKE_MATCH_1 AND NOT EXISTS "${CMAKE_MATCH_1}")
            message(STATUS "Removing stale CMake build dir with missing compiler ${CMAKE_MATCH_1}: ${build_dir}")
            set(_remove_build_dir ON)
        endif()
    endif()
    if(_remove_build_dir)
        scholia_remove_inside("${build_dir}" "${allowed_root}")
    endif()
    file(MAKE_DIRECTORY "${build_dir}")
endfunction()

function(scholia_run_vs command_line)
    if(NOT EXISTS "${VCVARS}")
        message(FATAL_ERROR "Cannot find vcvars64.bat: ${VCVARS}")
    endif()
    file(MAKE_DIRECTORY "${WORKSPACE_ROOT}/tmp")
    set(_cmd_file "${WORKSPACE_ROOT}/tmp/scholia-kf6-vs-env.cmd")
    file(WRITE "${_cmd_file}"
"@echo off
set \"PATH=${QT_PREFIX}/bin;${SDK_PREFIX}/bin;%PATH%\"
call \"${VCVARS}\" >nul
if errorlevel 1 exit /b %errorlevel%
${command_line}
")
    message(STATUS ">>> ${command_line}")
    execute_process(COMMAND cmd.exe /d /c "${_cmd_file}" RESULT_VARIABLE _result)
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "Command failed with exit code ${_result}: ${command_line}")
    endif()
endfunction()

function(scholia_ensure_git_checkout url ref destination)
    if(EXISTS "${destination}/.git")
        message(STATUS "Using existing checkout: ${destination}")
        execute_process(COMMAND git fetch --tags origin WORKING_DIRECTORY "${destination}" RESULT_VARIABLE _fetch_result)
        if(NOT _fetch_result EQUAL 0)
            message(WARNING "git fetch failed in ${destination}; trying local checkout for ${ref}.")
        endif()
        execute_process(COMMAND git checkout "${ref}" WORKING_DIRECTORY "${destination}" RESULT_VARIABLE _checkout_result)
        if(NOT _checkout_result EQUAL 0)
            message(FATAL_ERROR "git checkout ${ref} failed in ${destination}")
        endif()
        return()
    endif()

    if(EXISTS "${destination}")
        message(FATAL_ERROR "Source path exists but is not a git checkout: ${destination}")
    endif()

    get_filename_component(_parent "${destination}" DIRECTORY)
    file(MAKE_DIRECTORY "${_parent}")
    message(STATUS "Cloning ${url} -> ${destination}")
    execute_process(COMMAND git clone "${url}" "${destination}" RESULT_VARIABLE _clone_result)
    if(NOT _clone_result EQUAL 0)
        message(FATAL_ERROR "git clone failed for ${url}")
    endif()
    execute_process(COMMAND git checkout "${ref}" WORKING_DIRECTORY "${destination}" RESULT_VARIABLE _checkout_result)
    if(NOT _checkout_result EQUAL 0)
        message(FATAL_ERROR "git checkout ${ref} failed in ${destination}")
    endif()
endfunction()

function(scholia_find_msgfmt out_var sdk_prefix)
    set(_msgfmt "${sdk_prefix}/tools/gettext-native/bin/msgfmt.exe")
    if(NOT EXISTS "${_msgfmt}")
        message(FATAL_ERROR "Cannot find native Windows msgfmt at ${_msgfmt}. Run the gettext SDK step first.")
    endif()
    execute_process(COMMAND "${_msgfmt}" --version OUTPUT_VARIABLE _out ERROR_VARIABLE _err RESULT_VARIABLE _result)
    if(NOT _result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "GNU gettext-tools")
        message(FATAL_ERROR "Configured msgfmt is not GNU gettext-tools: ${_msgfmt}")
    endif()
    set(${out_var} "${_msgfmt}" PARENT_SCOPE)
endfunction()
